// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVVb4ILIwIFIA14xwGScBBESZTTrL64I',
    appId: '1:82766948392:web:f84aa148871a1ebbe96d1d',
    messagingSenderId: '82766948392',
    projectId: 'greenbudgetapp-project',
    authDomain: 'greenbudgetapp-project.firebaseapp.com',
    storageBucket: 'greenbudgetapp-project.appspot.com',
    measurementId: 'G-C3Q7CZZ4D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCac1Tz_jxqONUnV2efMw4r0K7j9jYx1OI',
    appId: '1:82766948392:android:5e64a3498aad8d47e96d1d',
    messagingSenderId: '82766948392',
    projectId: 'greenbudgetapp-project',
    storageBucket: 'greenbudgetapp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVHufYyzoFd4zCvxWepEQ9Kf_wVY_x6w',
    appId: '1:82766948392:ios:7388c3fb39d376e9e96d1d',
    messagingSenderId: '82766948392',
    projectId: 'greenbudgetapp-project',
    storageBucket: 'greenbudgetapp-project.appspot.com',
    iosBundleId: 'com.example.dontGoBroke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVHufYyzoFd4zCvxWepEQ9Kf_wVY_x6w',
    appId: '1:82766948392:ios:7388c3fb39d376e9e96d1d',
    messagingSenderId: '82766948392',
    projectId: 'greenbudgetapp-project',
    storageBucket: 'greenbudgetapp-project.appspot.com',
    iosBundleId: 'com.example.dontGoBroke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMVVb4ILIwIFIA14xwGScBBESZTTrL64I',
    appId: '1:82766948392:web:5d4f871449293d23e96d1d',
    messagingSenderId: '82766948392',
    projectId: 'greenbudgetapp-project',
    authDomain: 'greenbudgetapp-project.firebaseapp.com',
    storageBucket: 'greenbudgetapp-project.appspot.com',
    measurementId: 'G-H3089YQX5J',
  );
}
