// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe9lQo0qpeCtRwzxyRIfKf5XO1-fkCmYA',
    appId: '1:127457384617:web:06f472b97c4057729df1b8',
    messagingSenderId: '127457384617',
    projectId: 'don-t-go-broke-ac18f',
    authDomain: 'don-t-go-broke-ac18f.firebaseapp.com',
    databaseURL: 'https://don-t-go-broke-ac18f-default-rtdb.firebaseio.com',
    storageBucket: 'don-t-go-broke-ac18f.appspot.com',
    measurementId: 'G-HLQRL4QTZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnm5epPRNBkBxv2qT-KqAsG28VITCrjFM',
    appId: '1:127457384617:android:eb0ca01d3e68cdfe9df1b8',
    messagingSenderId: '127457384617',
    projectId: 'don-t-go-broke-ac18f',
    databaseURL: 'https://don-t-go-broke-ac18f-default-rtdb.firebaseio.com',
    storageBucket: 'don-t-go-broke-ac18f.appspot.com',
  );

}